# Generated by Django 5.1.1 on 2024-10-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_alter_trainer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(upload_to='trainers'),
        ),
    ]
