# Generated by Django 5.1.1 on 2024-10-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_booking_class_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclass',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
