# Generated by Django 5.1.1 on 2024-10-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_dailyprogress_dietingplan_eatingplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietingplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eatingplan',
            name='user',
        ),
    ]
