# Generated by Django 5.1.6 on 2025-02-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0014_alter_booking_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
