# Generated by Django 5.1.6 on 2025-02-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0003_trainer_user'),
    ]

    operations = [
    ]
